### ISSUE TITLE
About pretrain

### ISSUE THREAD

**Issue by Tianhuo007** [t04glovern/icface#1]
Hi,guys,  thanks your work. Could you provide another link for pretrain model？I can not get it from AWS.

**Comment by t04glovern** [comment]
If you can't use the AWS cli tool, you should be able to just pull the files directly.

https://s3.amazonaws.com/devopstar/resources/icface/gpubatch_resnet/latest_net_DA.pth
https://s3.amazonaws.com/devopstar/resources/icface/gpubatch_resnet/latest_net_G.pth
https://s3.amazonaws.com/devopstar/resources/icface/gpubatch_resnet/latest_net_GN.pth
https://s3.amazonaws.com/devopstar/resources/icface/gpubatch_resnet/latest_net_I_E.pth
